name: Build All Docker

on:
  schedule:
    - cron: "15 10 3 * *"
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log into docker
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Image
        run: docker-compose build
      - name: Push image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: docker-compose push